### PR TITLE
Send PacketDeclareCommand only when limbo is connected to proxy

### PR DESCRIPTION
**Pull request by MiGoYAm**
Limbo sends PacketDeclareCommand only when it is connected to proxy. I also changed command list to an empty one because it contained only one useless command.

### CODE REVIEW

**Comment by Nan1t** [comment]
Is there any reason to use Limbo without proxy, except tests?

**Comment by MiGoYAm** [comment]
No

**Comment by MiGoYAm** [comment]
Better?

**Comment by Nan1t** [comment]
Okay. Thank you for code improvements.

**Pull request merged**
