### PR TITLE
Added display of brand name under f3

### PR DESCRIPTION
**Pull request by MiGoYAm**

### CODE REVIEW

**Comment by Nan1t** [comment]
Thanks for PR! I have some suggestions.

1. As i know, brand name displays in debug screen since MC 1.13. Consider to register this packet for all versions that supports it, not for 1.18 only.
2. You should check client's version before sending this packet. Clients before 1.13 don't need to receive this.
3. This is cosmetic packet, so you can add ability to disable it. I think you can just check is this name `null`. This will be `null` if config param missing (for example, commented). So, above config param you can also note that this param can be commented (disabled).

**Comment by MiGoYAm** [comment]
Sorry, this are some of my private commits. 2 last commits should you check

**Comment by MiGoYAm** [comment]
I think theres no need to do the second part, because when i logged in into my fork i did it through 1.17 client and then the brand name was null(before "extend compatibilitiy for brand name" commit)

**Comment by MiGoYAm** [comment]
Done, I guess

**Comment by Nan1t** [comment]
Checked it. If disable brand, netty throws errror, because pre-encoded packet is null. You need to check this packet to null before sending. Also, on 1.17.1 i get client side error about invalid packet decoding. Seems like something wrong encoded here. Or packet registered under wrong id. You should check packet ID more carefully.

**Comment by MiGoYAm** [comment]
Done. I used packet IDs from incomplete page

**Comment by Nan1t** [comment]
Ok, now it works. Thanks for your PR!

**Pull request merged**
